module com.hamza.account {
    requires barbecue;
    requires javafx.swing;
    requires org.apache.poi.poi;
    requires org.apache.poi.ooxml;
    requires jasperreports;
    requires org.slf4j;
    requires commons.beanutils;
    requires com.hamza.controlsfx;
    requires lombok;
    requires annotations;
    requires org.apache.logging.log4j;
    requires java.sql;
    requires javafx.fxml;
    requires org.controlsfx.controls;
    requires de.jensd.fx.glyphs.fontawesome;
    requires com.jfoenix;
    requires json.simple;
    requires java.prefs;
    requires com.fasterxml.jackson.databind;
    requires jbcrypt;
    requires java.desktop;
    requires javafx.base;
    requires kernel;
    requires layout;
    requires io;
    requires javafx.graphics;
    requires javafx.controls;
    requires com.github.librepdf.openpdf;
    requires org.json;
//    requires spring.context;
//    requires spring.beans;
//    requires licensing.base;
//    requires typography;

    exports com.hamza.account.perm;
    exports com.hamza.account.model.domain;
    exports com.hamza.account.type;
    exports com.hamza.account.interfaces.impl_invoiceBuy;
    opens com.hamza.account.interfaces.impl_invoiceBuy to javafx.fxml;

    exports com.hamza.account.features.checkbox.api;
    opens com.hamza.account.features.checkbox.api to javafx.fxml;

    exports com.hamza.account.interfaces.impl_dataInterface;
    opens com.hamza.account.interfaces.impl_dataInterface to javafx.fxml;
    exports com.hamza.account.interfaces.api;
    opens com.hamza.account.interfaces.api to javafx.fxml;

    exports com.hamza.account.service;
    opens com.hamza.account.service to javafx.fxml;
    exports com.hamza.account.features.choiceDialoge;
    exports com.hamza.account.features.chart;
    opens com.hamza.account.features.chart to javafx.fxml;
    exports com.hamza.account.interfaces.treeAccount;
    opens com.hamza.account.interfaces.treeAccount to javafx.fxml;
    exports com.hamza.account.interfaces.implReportTotals;
    opens com.hamza.account.interfaces.implReportTotals to javafx.fxml;

    exports com.hamza.account.config;
    exports com.hamza.account.interfaces.impl_totalDesgin;
    opens com.hamza.account.interfaces.impl_totalDesgin to javafx.fxml;
    opens com.hamza.account.features.choiceDialoge to javafx.fxml;
    opens com.hamza.account.model.domain to javafx.fxml;
    exports com.hamza.account.interfaces.impl_design;
    opens com.hamza.account.interfaces.impl_design to javafx.fxml;
    exports com.hamza.account.table;
    exports com.hamza.account.view;
    opens com.hamza.account.view to javafx.fxml;
    exports com.hamza.account.features.checkbox.impl.setting;
    opens com.hamza.account.features.checkbox.impl.setting to javafx.fxml;
    exports com.hamza.account.model.dao;
    exports com.hamza.account.interfaces.impl_namesDao;
    opens com.hamza.account.interfaces.impl_namesDao to javafx.fxml;
    exports com.hamza.account.interfaces.spinner;
    opens com.hamza.account.interfaces.spinner to javafx.fxml;
    exports com.hamza.account.interfaces.impl_account;
    opens com.hamza.account.interfaces.impl_account to javafx.fxml;
    exports com.hamza.account.interfaces.names;
    opens com.hamza.account.interfaces.names to javafx.fxml;

    exports com.hamza.account.interfaces.treePurchase;
    opens com.hamza.account.interfaces.treePurchase to javafx.fxml;
    opens com.hamza.account.reportData to javafx.fxml;
    exports com.hamza.account.reportData;
    exports com.hamza.account.interfaces;
    opens com.hamza.account.interfaces to javafx.fxml;
    exports com.hamza.account.openFxml;
    opens com.hamza.account.openFxml;
    exports com.hamza.account.otherSetting;
    opens com.hamza.account.otherSetting to javafx.fxml;
    exports com.hamza.account.controller.dataByName;
    opens com.hamza.account.controller.dataByName to javafx.fxml;
    opens com.hamza.account.controller.invoice to javafx.fxml;
    exports com.hamza.account.controller.invoice;
    exports com.hamza.account.controller.convert_stock;
    opens com.hamza.account.controller.convert_stock to javafx.fxml;
    opens com.hamza.account.controller.model_print to javafx.fxml;
    exports com.hamza.account.controller.model_print;
    exports com.hamza.account.controller.convert_treasury;
    opens com.hamza.account.controller.convert_treasury to javafx.fxml;
    exports com.hamza.account.dash;
    opens com.hamza.account.dash to javafx.fxml;
    exports com.hamza.account.controller.search;
    opens com.hamza.account.controller.main to javafx.fxml;
    exports com.hamza.account.controller.main;
    exports com.hamza.account.controller.setting;
    opens com.hamza.account.controller.setting to javafx.fxml;
    exports com.hamza.account.controller.others;
    opens com.hamza.account.controller.others to javafx.fxml;
    exports com.hamza.account.controller.reports;
    opens com.hamza.account.controller.reports to javafx.fxml;
    exports com.hamza.account.controller.name_account;
    opens com.hamza.account.controller.name_account to javafx.fxml;
    exports com.hamza.account.controller.items;
    opens com.hamza.account.controller.items to javafx.fxml;
    exports com.hamza.account.controller.users;
    opens com.hamza.account.controller.users to javafx.fxml;
    opens com.hamza.account.table;
    exports com.hamza.account.view.barcode;
    opens com.hamza.account.view.barcode to javafx.fxml;
    exports com.hamza.account.features.notification;
    opens com.hamza.account.features.notification to javafx.fxml;
    exports com.hamza.account.controller.dataSetting;
    opens com.hamza.account.controller.dataSetting to javafx.fxml;
    exports com.hamza.account.controller.dataSetting.impl;
    opens com.hamza.account.controller.dataSetting.impl to javafx.fxml;
    exports com.hamza.account.controller.dataByName.impl;
    opens com.hamza.account.controller.dataByName.impl to javafx.fxml;
    exports com.hamza.account.model.base;
    opens com.hamza.account.model.base to javafx.fxml;
    exports com.hamza.account.controller.target;
    opens com.hamza.account.controller.target to javafx.fxml;
    exports com.hamza.account;
    opens com.hamza.account to javafx.fxml;
    opens com.hamza.account.config;
    exports com.hamza.account.controller.reports.model;
    opens com.hamza.account.controller.reports.model to javafx.fxml;
    exports com.hamza.account.controller.pos;
    opens com.hamza.account.controller.pos to javafx.fxml;
    exports com.hamza.account.features.key_setting;
    opens com.hamza.account.features.key_setting to javafx.fxml;
    exports com.hamza.account.view.calculator;
    exports com.hamza.account.controller.calculator;
    opens com.hamza.account.view.calculator to javafx.fxml;
    opens com.hamza.account.controller.calculator to javafx.fxml;
    exports com.hamza.account.features.export;
    opens com.hamza.account.features.export;
}