package com.hamza.account.controller.name_account;

import com.hamza.account.features.party.ageing.AgeingBucket;
import com.hamza.account.features.party.ageing.PartyAgeingRow;
import com.hamza.controlsfx.language.LanguageManager;
import com.hamza.controlsfx.excel.WriteExcelInterface;

import java.util.ArrayList;
import java.util.List;

/**
 * The ageing report as a spreadsheet.
 * <p>
 * The columns are built from {@link AgeingBucket#inReadingOrder()} rather than written out, so
 * the file and the screen cannot come to hold different bands in different orders - the header
 * and the row are generated by the same loop.
 * <p>
 * The rows are the whole filtered set, read again by {@code forExport} with the filter the table
 * used, never the rows on screen.
 */
public record PartyAgeingExcelWriter(List<PartyAgeingRow> rows)
        implements WriteExcelInterface<PartyAgeingRow> {

    @Override
    public Object[] columnHeader() {
        var lm = LanguageManager.getInstance();
        List<Object> header = new ArrayList<>(List.of(
                lm.getString("code"), lm.getString("name"), lm.getString("column.tel"),
                lm.getString("party.column.area"), lm.getString("party.ageing.column.terms")));
        for (AgeingBucket bucket : AgeingBucket.inReadingOrder()) {
            header.add(lm.getString(bucket.messageKey()));
        }
        header.add(lm.getString("party.ageing.column.unallocated"));
        header.add(lm.getString("party.ageing.column.balance"));
        return header.toArray();
    }

    @Override
    public Object[] dataRow(PartyAgeingRow row) {
        List<Object> cells = new ArrayList<>(List.of(
                row.partyId(), row.name(), row.phone(), row.areaName(), row.paymentTerms()));
        for (AgeingBucket bucket : AgeingBucket.inReadingOrder()) {
            cells.add(row.amount(bucket));
        }
        cells.add(row.unallocated());
        cells.add(row.balance());
        return cells.toArray();
    }

    @Override
    public List<PartyAgeingRow> itemsList() {
        return rows;
    }

    @Override
    public boolean addDataToFile() {
        return true;
    }

    @Override
    public String sheetName() {
        return LanguageManager.getInstance().getString("party.ageing.export.sheet");
    }
}
