account=Accounts
activated=Activated
add=Add
add_group=Add Group
addItem=Add Item
address=Address
addUser=Add User
Administrator=Administrator
Alerts=Alerts
all=All
allRights=All rights reserved © 2020
ar=Arabic
background=Background Color
backup=Backup
balance=Balance
barcode=Barcode
basic=Basic Information
box=Box
BuyPrice=Purchasing Price
cancel=Cancel
case=Case
cash=Cash
change=Change
changeApp=Appearance
choose=Choose
choose_column=Choose columns in the table
choose_file=Choose file
close=Close
code=Code
collapse=Collapse All
commercial=Commercial Record
confirm=Confirm Password
count=Count
cuAcc=Customer Accounts
customData=Customers
date=Date
defer=Defer
delete=Delete
discount=Discount
dueDate=Due Date
en=English
enter=Enter
error=Error
expand=Expand All
fColor=Font Color
font=Font
from=From
groupCode=Group Code
groups=Groups
in_active=Not Active
items=Items
language=Language
lastUpdated=Last Updated
logout=Logout
main=Main Screen
mainGroup=Main Group
name=Name
new=New
newPass=New Password
nPiece=Number Of Pieces
num=Num
numInv=Number
numItems=Number Of Items
oldPass=Old Password
open=Open
others=Others
paid=Paid
password=Password
permissions=User Permissions
piece=Piece
pMovement=Purchase Movement
price=Price
print=Print
normalPrinter=Normal Printer
print2=Thermal Printer
pur=Purchase
quantity=Quantity
QueryPrice=Query The Price
rate=Rate
recovery=Recovery
refresh=Refresh
report=Reports
RePur=Returned Purchases
ReSal=Sales Returns
rest=The Rest
sales=Sales
save=Save
search=Search
search_date=Search By Date
search_name=Search By Name
selPrice=Selling Price
settingList=Setting
show=Show
stock=Stock
stocktaking=StockTaking
subGroup=Sub Group
supAcc=Vendor Accounts
tax=Tax Card
tel=Telephone
time=Time
to=To
total=Total
totalAfter=After Discount
type=Type
unit=Unit
update=Update
users=Users
year=Year
updateItem=Update Item
deposit=Deposits
expensesDetails=Expenses
employees=Employees
insert=Insert
firstBalance=First Balance
customers=Customers
suppliers=Suppliers
CONVERT=Convert
NAME_DELEGATE=Delegate name
expenses=Expenses
invoice.short.no=No:
invoice.date=Date:
invoice.admin=Admin:
invoice.number=Invoice No:
invoice.entry.time=Entry Time:
invoice.customer.name=Name:
invoice.total.col=Total
invoice.item.col=Item
invoice.price.col=Price
invoice.qty.col=Qty
invoice.discount.col=Discount
invoice.total=Total:
invoice.discount=Discount:
invoice.delivery=Delivery:
invoice.address=Address:
invoice.tel=Tel:
