OK=OK
CANCEL=Cancel
WRONG=Wrong
SAVE_DONE=Saved
SAVE_ALL_DATA=Save All Data
DELETE_DONE=Deleted
DELETE_DATA=Delete Data
DELETE_ALL_DATA=Delete All Data
DELETE=Delete
DO_YOU_WANT=Do You Want
DATA=Data
ALL_DATA=All Data
BACKUP=Backup
CLOSE=Close
SAVE=Save
CHOOSE=Choose File
RECOVERY=Recovery
HOUR=Hour
WHERE_TO_SAVE=Where File Save
SAVING_TIME=Saving Time
ENTER=Enter
PASSWORD=Password
SHOW=Show
USERNAME=Username
COPY_RIGHT=Copyright
SCREEN_LOGIN=Login Screen
PLEASE_WAIT=Please Wait
DATE=Date
TIME=Time
SYSTEM=System
COMPUTER_NAME=Computer Name
DOWNLOAD_THE_DATABASE=Load Database
SAVE_BEFORE_CLOSE=Save Before Close
AUTOMATIC_BACKUP=Automatic Backup
MESSAGE=No File Found
LOCATION_IS_NOT_SET=Location is not set
PLEASE_ENTER_YOUR_SYSTEM_PASSWORD=Please Enter Your System Password